routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth'], function() {

Route::resource('/items', App\Http\Controllers\ItemController::class)->only(['index', 'show','create','store']);
Route::resource('/bid-logs', App\Http\Controllers\BidLogController::class)->only(['store', 'index']);
Route::resource('/settings', App\Http\Controllers\SettingController::class)->only(['create', 'store']);

//apis
Route::post('/api/set-auto-bid', [App\Http\Controllers\ItemController::class,'setAutoBid'])->name('api.set-auto-bid');
Route::post('/api/search-items', [App\Http\Controllers\ItemController::class,'searchItems'])->name('api.search-items');

// user management
Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
});

Route::get('/', function () {
    return view('auth/login');
});

resources/views/layouts/navbars/sidebar.blade.php
<div class="sidebar" data-color="orange" data-background-color="white" data-image="{{ asset('material') }}/img/sidebar-1.jpg">
    <div class="logo">
        <a href="#" class="simple-text logo-normal">
            {{ config('app.name') }}
        </a>
        <div class="simple-text">
         <h6> User: {{ Auth::user()->name ?? null }}</h6>
         </div>
    </div>

    @if(!isset($activePage))
    @php
    $$activePage = "";
    @endphp
    @endIf
    @if(!isset($titlePage))
    @php
    $titlePage = "";
    @endphp
    @endIf
    <div class="sidebar-wrapper">
        <ul class="nav">
            <li class="nav-item{{ $activePage == 'items' ? ' active' : '' }}">
                <a class="nav-link" href="{{ route('items.index') }}">
                    <i class="material-icons">dashboard</i>
                    <p>{{ __('Item List') }}</p>
                </a>
            </li>
            <li class="nav-item {{ ($activePage == 'admin' || $activePage == 'settings') ? ' active' : '' }}">
                <a class="nav-link" data-toggle="collapse" href="#laravelExample" aria-expanded="true">
                    <i class="material-icons">settings</i>
                    <p>{{ __('Settings') }}
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse show" id="laravelExample">
                    <ul class="nav">
                        <li class="nav-item{{ $activePage == 'admin' ? ' active' : '' }}">
                            <a class="nav-link" href="{{ route('items.create') }}">
                                <i class="material-icons">manage_accounts</i>
                                <p>{{ __('Admin Settings') }}</p>
                            </a>
                        </li>
                        <li class="nav-item{{ $activePage == 'setting' ? ' active' : '' }}">
                            <a class="nav-link" href="{{ route('settings.create') }}">
                                <i class="material-icons">watch_later</i>
                                <p>{{ __('Max Bid Amount') }}</p>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
</div>